spring:
  data:
    mongodb:
      uri: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.2"
      database: "umbrella"

  banner:
    location: banner.txt

rsa:
  rsaPrivateKey: classpath:Keys/private.pem
  rsaPublicKey: classpath:Keys/public.pem

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger-docs

umbrella:
  variables:
    jwt:
      expire:
        days: 7