server:
  port: 8090

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: APIGateway
  banner:
    location: banner.txt
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false